apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: yoadw20/crud-app
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: DB_HOST
              value: postgres-cluster-ip-service
            - name: DB_PORT
              value: --
            - name: DB_USER
              value: --
            - name: DB_DATABASE
              value: --
            - name: DB_PASSWORD
              value: --
            - name: ConnectionStrings__BloggingContext
              value: server=sql11.freemysqlhosting.net;database=sql11666835;Uid=sql11666835;Pwd=Aft6tGP7Mf;
